#############################################################################
# Makefile for building: microManage_server
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 28 17:50:18 2013
# Project:  microManage_server.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile microManage_server.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		micromachine.cpp \
		micromanager.cpp \
		qprocessmanager_simple.cpp \
		qemuvm_qprocess.cpp moc_micromachine.cpp \
		moc_micromanager.cpp \
		moc_qemuvm_qprocess.cpp
OBJECTS       = main.o \
		micromachine.o \
		micromanager.o \
		qprocessmanager_simple.o \
		qemuvm_qprocess.o \
		moc_micromachine.o \
		moc_micromanager.o \
		moc_qemuvm_qprocess.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		microManage_server.pro
QMAKE_TARGET  = microManage_server
DESTDIR       = 
TARGET        = microManage_server

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: microManage_server.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile microManage_server.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile microManage_server.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/microManage_server1.0.0 || $(MKDIR) .tmp/microManage_server1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/microManage_server1.0.0/ && $(COPY_FILE) --parents micromachine.h micromanager.h qprocessmanager_simple.h qemuvm_qprocess.h .tmp/microManage_server1.0.0/ && $(COPY_FILE) --parents main.cpp micromachine.cpp micromanager.cpp qprocessmanager_simple.cpp qemuvm_qprocess.cpp .tmp/microManage_server1.0.0/ && (cd `dirname .tmp/microManage_server1.0.0` && $(TAR) microManage_server1.0.0.tar microManage_server1.0.0 && $(COMPRESS) microManage_server1.0.0.tar) && $(MOVE) `dirname .tmp/microManage_server1.0.0`/microManage_server1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/microManage_server1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_micromachine.cpp moc_micromanager.cpp moc_qemuvm_qprocess.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_micromachine.cpp moc_micromanager.cpp moc_qemuvm_qprocess.cpp
moc_micromachine.cpp: micromachine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) micromachine.h -o moc_micromachine.cpp

moc_micromanager.cpp: qemuvm_qprocess.h \
		micromachine.h \
		micromanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) micromanager.h -o moc_micromanager.cpp

moc_qemuvm_qprocess.cpp: micromachine.h \
		qemuvm_qprocess.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qemuvm_qprocess.h -o moc_qemuvm_qprocess.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

micromachine.o: micromachine.cpp micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o micromachine.o micromachine.cpp

micromanager.o: micromanager.cpp micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o micromanager.o micromanager.cpp

qprocessmanager_simple.o: qprocessmanager_simple.cpp qprocessmanager_simple.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprocessmanager_simple.o qprocessmanager_simple.cpp

qemuvm_qprocess.o: qemuvm_qprocess.cpp qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qemuvm_qprocess.o qemuvm_qprocess.cpp

moc_micromachine.o: moc_micromachine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_micromachine.o moc_micromachine.cpp

moc_micromanager.o: moc_micromanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_micromanager.o moc_micromanager.cpp

moc_qemuvm_qprocess.o: moc_qemuvm_qprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qemuvm_qprocess.o moc_qemuvm_qprocess.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

