#############################################################################
# Makefile for building: microManage_server
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat Jun 15 22:03:25 2013
# Project:  microManage_server.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile microManage_server.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/usr/include -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		micromachine.cpp \
		micromanager.cpp \
		qprocessmanager_simple.cpp \
		qemuvm_qprocess.cpp \
		experiment.cpp \
		sampler.cpp \
		../perfdata/perfSampler.cpp \
		../perfdata/memDataPoint.cpp \
		../perfdata/cpuSample2.cpp \
		../perfdata/scalingSample.cpp moc_micromachine.cpp \
		moc_micromanager.cpp \
		moc_qemuvm_qprocess.cpp \
		moc_experiment.cpp \
		moc_sampler.cpp \
		moc_perfSampler.cpp
OBJECTS       = main.o \
		micromachine.o \
		micromanager.o \
		qprocessmanager_simple.o \
		qemuvm_qprocess.o \
		experiment.o \
		sampler.o \
		perfSampler.o \
		memDataPoint.o \
		cpuSample2.o \
		scalingSample.o \
		moc_micromachine.o \
		moc_micromanager.o \
		moc_qemuvm_qprocess.o \
		moc_experiment.o \
		moc_sampler.o \
		moc_perfSampler.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		microManage_server.pro
QMAKE_TARGET  = microManage_server
DESTDIR       = 
TARGET        = microManage_server

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: microManage_server.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile microManage_server.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile microManage_server.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/microManage_server1.0.0 || $(MKDIR) .tmp/microManage_server1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/microManage_server1.0.0/ && $(COPY_FILE) --parents micromachine.h micromanager.h qprocessmanager_simple.h qemuvm_qprocess.h experiment.h sampler.h ../perfdata/perfSampler.h ../perfdata/memDataPoint.h ../perfdata/cpuSample2.h outstream.h ../perfdata/scalingSample.h .tmp/microManage_server1.0.0/ && $(COPY_FILE) --parents main.cpp micromachine.cpp micromanager.cpp qprocessmanager_simple.cpp qemuvm_qprocess.cpp experiment.cpp sampler.cpp ../perfdata/perfSampler.cpp ../perfdata/memDataPoint.cpp ../perfdata/cpuSample2.cpp ../perfdata/scalingSample.cpp .tmp/microManage_server1.0.0/ && (cd `dirname .tmp/microManage_server1.0.0` && $(TAR) microManage_server1.0.0.tar microManage_server1.0.0 && $(COMPRESS) microManage_server1.0.0.tar) && $(MOVE) `dirname .tmp/microManage_server1.0.0`/microManage_server1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/microManage_server1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_micromachine.cpp moc_micromanager.cpp moc_qemuvm_qprocess.cpp moc_experiment.cpp moc_sampler.cpp moc_perfSampler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_micromachine.cpp moc_micromanager.cpp moc_qemuvm_qprocess.cpp moc_experiment.cpp moc_sampler.cpp moc_perfSampler.cpp
moc_micromachine.cpp: micromachine.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ micromachine.h -o moc_micromachine.cpp

moc_micromanager.cpp: qemuvm_qprocess.h \
		micromachine.h \
		micromanager.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ micromanager.h -o moc_micromanager.cpp

moc_qemuvm_qprocess.cpp: micromachine.h \
		qemuvm_qprocess.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qemuvm_qprocess.h -o moc_qemuvm_qprocess.cpp

moc_experiment.cpp: micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h \
		../perfdata/perfSampler.h \
		../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/scalingSample.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h \
		outstream.h \
		experiment.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ experiment.h -o moc_experiment.cpp

moc_sampler.cpp: sampler.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sampler.h -o moc_sampler.cpp

moc_perfSampler.cpp: ../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/scalingSample.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h \
		outstream.h \
		micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h \
		../perfdata/perfSampler.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../perfdata/perfSampler.h -o moc_perfSampler.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

micromachine.o: micromachine.cpp micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o micromachine.o micromachine.cpp

micromanager.o: micromanager.cpp micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h \
		experiment.h \
		../perfdata/perfSampler.h \
		../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/scalingSample.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h \
		outstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o micromanager.o micromanager.cpp

qprocessmanager_simple.o: qprocessmanager_simple.cpp qprocessmanager_simple.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprocessmanager_simple.o qprocessmanager_simple.cpp

qemuvm_qprocess.o: qemuvm_qprocess.cpp qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qemuvm_qprocess.o qemuvm_qprocess.cpp

experiment.o: experiment.cpp experiment.h \
		micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h \
		../perfdata/perfSampler.h \
		../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/scalingSample.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h \
		outstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o experiment.o experiment.cpp

sampler.o: sampler.cpp sampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sampler.o sampler.cpp

perfSampler.o: ../perfdata/perfSampler.cpp ../perfdata/perfSampler.h \
		../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/scalingSample.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h \
		outstream.h \
		micromanager.h \
		qemuvm_qprocess.h \
		micromachine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perfSampler.o ../perfdata/perfSampler.cpp

memDataPoint.o: ../perfdata/memDataPoint.cpp ../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memDataPoint.o ../perfdata/memDataPoint.cpp

cpuSample2.o: ../perfdata/cpuSample2.cpp ../perfdata/cpuSample2.h \
		../perfdata/globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpuSample2.o ../perfdata/cpuSample2.cpp

scalingSample.o: ../perfdata/scalingSample.cpp ../perfdata/scalingSample.h \
		../perfdata/cpuSample2.h \
		../perfdata/globals.h \
		../perfdata/memDataPoint.h \
		../perfdata/dataPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scalingSample.o ../perfdata/scalingSample.cpp

moc_micromachine.o: moc_micromachine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_micromachine.o moc_micromachine.cpp

moc_micromanager.o: moc_micromanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_micromanager.o moc_micromanager.cpp

moc_qemuvm_qprocess.o: moc_qemuvm_qprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qemuvm_qprocess.o moc_qemuvm_qprocess.cpp

moc_experiment.o: moc_experiment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_experiment.o moc_experiment.cpp

moc_sampler.o: moc_sampler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sampler.o moc_sampler.cpp

moc_perfSampler.o: moc_perfSampler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_perfSampler.o moc_perfSampler.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

